# Logistic Regression Model

In [ ]:
import pandas as pd
import numpy as np
import math as mt

# **Import Train CSV file for training the model**
Using Pandas Module to import CSV and stored into a Dataframe and Converted the Dataframe into Numpy Array for performing various Operations.<br>
X is the variable for Train Data Array.
Y is the ground Truth such that <br>
Y = W1 + W2*(x1) + w3*(x2)
<br>
x1 is for Pclass and x2 is for sex.


In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/vanshbansal1505/ICG-Summer-Program-2021-DS/main/Assignment-1/data/train.csv",usecols = ['Survived','Pclass','Sex'])
df.dropna(inplace = True)
for x in df.index:
  if df.loc[x, "Sex"] == "male":
    df.loc[x, "Sex"] = 1
  else :
    df.loc[x, "Sex"] = 0
X = df.to_numpy()
X = X.astype(np.float64)
Y = X[:,0]
Y = Y.reshape(-1,1)
X = X[:,1:]
R = np.ones((1,len(X)),np.float64)
X = np.insert(X,0,R,axis=1)
print(X)

[[1. 3. 1.]
 [1. 1. 0.]
 [1. 3. 0.]
 ...
 [1. 3. 0.]
 [1. 2. 0.]
 [1. 2. 1.]]


# **Import Test CSV file for testing the model**
Using Pandas Module to import CSV and stored into a Dataframe and Converted the Dataframe into Numpy Array for performing various Operations.<br>
K is the variable for Test Data Array.

In [ ]:
dk = pd.read_csv("https://raw.githubusercontent.com/vanshbansal1505/ICG-Summer-Program-2021-DS/main/Assignment-1/data/test.csv",usecols = ['Pclass','Sex'])
dk.dropna(inplace = True)
for x in dk.index:
  if dk.loc[x, "Sex"] == "male":
    dk.loc[x, "Sex"] = 1
  else :
    dk.loc[x, "Sex"] = 0
K = dk.to_numpy()
K = K.astype(np.float64)
R = np.ones((1,len(K)),np.float64)
K = np.insert(K,0,R,axis=1)
print(K)

[[1. 3. 1.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 1. 1.]
 [1. 2. 1.]
 [1. 1. 0.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 3. 0.]
 [1. 2. 0.]
 [1. 3. 1.]
 [1. 2. 1.]
 [1. 3. 0.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 1. 0.]
 [1. 3. 0.]
 [1. 3. 1.]
 [1. 3. 0.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 3. 0.]
 [1. 3. 1.]
 [1. 2. 0.]
 [1. 3. 1.]
 [1. 3. 0.]
 [1. 3. 0.]
 [1. 2. 1.]
 [1. 3. 1.]
 [1. 3. 0.]
 [1. 2. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 1. 0.]
 [1. 2. 0.]
 [1. 1. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 3. 0.]
 [1. 3. 0.]
 [1. 1. 1.]
 [1. 3. 0.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 3. 0.]
 [1. 3. 1.]
 [1. 3. 1.]
 [1. 1. 1.]
 [1. 2. 1.]
 [1. 3. 1.]
 [1. 3. 0.]
 [1. 1. 1.]
 [1. 3. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 3. 0.]
 [1.

### **Used stochastic gradient descent algorithm for finding the theta matrix for the model which will be used to predict the Data**

## ***alpha*** is the model learning rate<br>
*For small value of alpha value is not overflowing*

In [ ]:
theta = np.zeros((3,1),np.float64)
alpha = 1
for j in range(0,3):
  for i in range(0,len(K)):
    theta[j] = theta[j] + alpha*(np.matmul((Y[i]-np.matmul(K[i],theta)),[K[i][j]]))
print(theta)

[[ 0.]
 [-8.]
 [24.]]


## Predicted the result for the model from test Data 

In [ ]:
G = np.matmul(K,theta)

def sigmoid(integer):
  if integer>0:
    return 1
  else:
    return 0

output = [sigmoid(i[0]) for i in G.tolist()]
predicted = np.array(output)
predicted = np.reshape(predicted,(-1,1))
print(predicted)

[[0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]


# **Accuracy and Error of This Model:**

In [ ]:
dt = pd.read_csv("https://raw.githubusercontent.com/vanshbansal1505/ICG-Summer-Program-2021-DS/main/Assignment-1/data/test.csv",usecols = ['Survived','Sex'])
dt.dropna(inplace = True)
for x in dt.index:
  if dt.loc[x, "Sex"] == "male":
    dt.loc[x, "Sex"] = 1
  else :
    dt.loc[x, "Sex"] = 0
grnd_truth = dt.to_numpy()
grnd_truth = grnd_truth.astype(np.float64)
grnd_truth = grnd_truth[:,0]
count = 0;
for i in range(0,len(K)):
  if(predicted[i]==[grnd_truth[i]]): count=count+1

print("Accuracy of this logistic Model is :")
print((count/len(K))*100)
print("for alpha = ",alpha)

print("Error of this logistic Model is :")
print((1-count/len(K))*100)
print("for alpha = ",alpha)


Accuracy of this logistic Model is :
53.13653136531366
for alpha =  1
Error of this logistic Model is :
46.86346863468634
for alpha =  1
