In [1]:
import numpy as np
import pandas as pd

train_dat = pd.read_csv("train.csv")
test_dat = pd.read_csv("test.csv")

In [2]:
print(train_dat[:10], train_dat.shape ,sep = '\n\n')

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            1         0       3    male  22.0      1      0   7.2500
1            2         1       1  female  38.0      1      0  71.2833
2            3         1       3  female  26.0      0      0   7.9250
3            4         1       1  female  35.0      1      0  53.1000
4            5         0       3    male  35.0      0      0   8.0500
5            6         0       3    male   NaN      0      0   8.4583
6            7         0       1    male  54.0      0      0  51.8625
7            8         0       3    male   2.0      3      1  21.0750
8            9         1       3  female  27.0      0      2  11.1333
9           10         1       2  female  14.0      1      0  30.0708

(620, 8)


In [3]:
train_dat1 = train_dat.copy()
test_dat1 = test_dat.copy()

In [4]:
train_dat1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  620 non-null    int64  
 1   Survived     620 non-null    int64  
 2   Pclass       620 non-null    int64  
 3   Sex          620 non-null    object 
 4   Age          489 non-null    float64
 5   SibSp        620 non-null    int64  
 6   Parch        620 non-null    int64  
 7   Fare         620 non-null    float64
dtypes: float64(2), int64(5), object(1)
memory usage: 38.9+ KB


In [5]:
target = train_dat1.Survived.copy()
test_target = test_dat1.Survived.copy()
train_dat1.drop(['PassengerId','Survived'],axis = 1, inplace = True)
test_dat1.drop(['PassengerId','Survived'],axis = 1,inplace = True)
target, train_dat1.head(), test_target, train_dat1.head()

(0      0
 1      1
 2      1
 3      1
 4      0
       ..
 615    1
 616    0
 617    0
 618    1
 619    0
 Name: Survived, Length: 620, dtype: int64,
    Pclass     Sex   Age  SibSp  Parch     Fare
 0       3    male  22.0      1      0   7.2500
 1       1  female  38.0      1      0  71.2833
 2       3  female  26.0      0      0   7.9250
 3       1  female  35.0      1      0  53.1000
 4       3    male  35.0      0      0   8.0500,
 0      0
 1      1
 2      1
 3      0
 4      0
       ..
 266    0
 267    1
 268    0
 269    1
 270    0
 Name: Survived, Length: 271, dtype: int64,
    Pclass     Sex   Age  SibSp  Parch     Fare
 0       3    male  22.0      1      0   7.2500
 1       1  female  38.0      1      0  71.2833
 2       3  female  26.0      0      0   7.9250
 3       1  female  35.0      1      0  53.1000
 4       3    male  35.0      0      0   8.0500)

In [6]:
train_dat1.Age.mean(), train_dat1.Age.median(), train_dat1.Age.std(), test_dat1.Age.mean(), test_dat1.Age.median(), test_dat1.Age.std()

(29.78118609406953,
 28.0,
 14.4049979025998,
 29.520755555555557,
 28.0,
 14.817980416474299)

In [7]:
train_dat1.Age.fillna(28,inplace = True), test_dat1.Age.fillna(28,inplace = True)
train_dat1.info(), test_dat1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  620 non-null    int64  
 1   Sex     620 non-null    object 
 2   Age     620 non-null    float64
 3   SibSp   620 non-null    int64  
 4   Parch   620 non-null    int64  
 5   Fare    620 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 29.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  271 non-null    int64  
 1   Sex     271 non-null    object 
 2   Age     271 non-null    float64
 3   SibSp   271 non-null    int64  
 4   Parch   271 non-null    int64  
 5   Fare    271 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 12.8+ KB


(None, None)

In [8]:
sex = pd.get_dummies(train_dat1.Sex)
sex.columns = ['s_f','s_m']
clas = pd.get_dummies(train_dat1.Pclass)
train_dat1 = pd.concat([train_dat1,sex,clas],axis = 1)
train_dat1.drop(['Sex','Pclass'], axis = 1, inplace = True)
train_dat1.head()

Age  SibSp  Parch     Fare  s_f  s_m  1  2  3
0  22.0      1      0   7.2500    0    1  0  0  1
1  38.0      1      0  71.2833    1    0  1  0  0
2  26.0      0      0   7.9250    1    0  0  0  1
3  35.0      1      0  53.1000    1    0  1  0  0
4  35.0      0      0   8.0500    0    1  0  0  1

In [9]:
t_sex = pd.get_dummies(test_dat1.Sex)
t_sex.columns = ['s_f','s_m']
t_clas = pd.get_dummies(test_dat1.Pclass)
test_dat1 = pd.concat([test_dat1,t_sex,t_clas],axis = 1)
test_dat1.drop(['Sex','Pclass'], axis = 1, inplace = True)
test_dat1.head()

Age  SibSp  Parch     Fare  s_f  s_m  1  2  3
0  27.0      1      0  14.4542    0    1  0  0  1
1  42.0      1      0  52.5542    0    1  1  0  0
2  20.0      1      1  15.7417    0    1  0  0  1
3  21.0      0      0   7.8542    0    1  0  0  1
4  21.0      0      0  16.1000    0    1  0  0  1

In [10]:
col = ['Age','SibSp','Parch','Fare']
train_dat1[col] = (train_dat1[col] - train_dat1[col].min())/(train_dat1[col].max() - train_dat1[col].min())
test_dat1[col] = (test_dat1[col] - test_dat1[col].min())/(test_dat1[col].max() - test_dat1[col].min())
train_dat1, test_dat1

(          Age  SibSp  Parch      Fare  s_f  s_m  1  2  3
 0    0.302491  0.125    0.0  0.014151    0    1  0  0  1
 1    0.530249  0.125    0.0  0.139136    1    0  1  0  0
 2    0.359431  0.000    0.0  0.015469    1    0  0  0  1
 3    0.487544  0.125    0.0  0.103644    1    0  1  0  0
 4    0.487544  0.000    0.0  0.015713    0    1  0  0  1
 ..        ...    ...    ...       ...  ...  ... .. .. ..
 615  0.330961  0.125    0.4  0.126872    1    0  0  1  0
 616  0.473310  0.125    0.2  0.028107    0    1  0  0  1
 617  0.359431  0.125    0.0  0.031425    1    0  0  0  1
 618  0.046263  0.250    0.2  0.076123    1    0  0  1  0
 619  0.359431  0.000    0.0  0.020495    0    1  0  1  0
 
 [620 rows x 9 columns],
           Age  SibSp     Parch      Fare  s_f  s_m  1  2  3
 0    0.334004  0.125  0.000000  0.028213    0    1  0  0  1
 1    0.522493  0.125  0.000000  0.102579    0    1  1  0  0
 2    0.246042  0.125  0.166667  0.030726    0    1  0  0  1
 3    0.258608  0.000  0.000000  

In [11]:
data = train_dat1.to_numpy().T
targ = target.to_numpy()
t_data = test_dat1.to_numpy().T
t_targ = test_target.to_numpy()
data, targ, t_data, t_targ, t_data.shape, t_targ.shape

(array([[0.3024911 , 0.53024911, 0.3594306 , ..., 0.3594306 , 0.04626335,
         0.3594306 ],
        [0.125     , 0.125     , 0.        , ..., 0.125     , 0.25      ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.2       ,
         0.        ],
        ...,
        [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
         1.        ],
        [1.        , 0.        , 1.        , ..., 1.        , 0.        ,
         0.        ]]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [12]:
model = np.array([np.ones((9)),np.ones(1)])
model, (np.array([[1,2],[3,4]]) - np.array([[1,2]])), np.array([np.array([1,2]).sum()])

(array([array([1., 1., 1., 1., 1., 1., 1., 1., 1.]), array([1.])],
       dtype=object),
 array([[0, 0],
        [2, 2]]),
 array([3]))

In [13]:
(model[0].dot(data) + model[1]).shape

(620,)

In [14]:
def sigmoid(dat):
    return 1/(1+np.exp(-dat))
(sigmoid(model[0].dot(data) + model[1]) - targ).shape

(620,)

In [15]:
def loss(model, data, targ):
    pred_prob = sigmoid(model[0].dot(data) + model[1])
    return -(targ*(np.log(pred_prob)) + (1-targ)*(np.log(1-pred_prob)))
loss(model,data,targ).shape

(620,)

In [16]:
def grad(model, data, targ):
    l = len(targ)
    diff = (sigmoid(model[0].dot(data) + model[1]) - targ).reshape(l,1)
    sums = (data.dot(diff)/l).sum(axis = 1)
    return np.array([sums, np.array([diff.sum()/l])])
grad(model, data, targ)

array([array([0.24342595, 0.04157825, 0.0379007 , 0.02672099, 0.08394728,
       0.49528783, 0.09137094, 0.09576608, 0.3920981 ]),
       array([0.57923512])], dtype=object)

In [17]:
model = np.array([np.ones((9)),np.ones(1)])

In [18]:
epochs = 100000
lr_rate = 0.1

for i in range(epochs):
    model -= lr_rate * grad(model, data, targ)
los = loss(model, data, target).sum()/len(targ)

In [19]:
model, data, target, data.shape, target.shape

(array([array([-2.55291734, -2.51954586, -0.24152605, -0.70670845,  1.95267008,
        -0.83912376,  1.71201359,  0.82325008, -0.42171736]),
        array([0.11354631])], dtype=object),
 array([[0.3024911 , 0.53024911, 0.3594306 , ..., 0.3594306 , 0.04626335,
         0.3594306 ],
        [0.125     , 0.125     , 0.        , ..., 0.125     , 0.25      ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.2       ,
         0.        ],
        ...,
        [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
         1.        ],
        [1.        , 0.        , 1.        , ..., 1.        , 0.        ,
         0.        ]]),
 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 615    1
 616    0
 617    0
 618    1
 619    0
 Name: Survived, Length: 620, dtype: int64,
 (9, 620),
 (620,))

In [20]:
los

0.45014931060692775

In [21]:
def predic(x):
    if x>=0.5:
        return 1
    else:
        return 0

predic_v = np.vectorize(predic)
pred = predic_v(sigmoid(model[0].dot(data) + model[1]))
l = len(targ)
accuracy = (1 - np.abs(pred-targ).sum()/l)*100
t_pred = predic_v(sigmoid(model[0].dot(t_data) + model[1]))
l = len(t_targ)
t_accuracy = (1 - np.abs(t_pred-t_targ).sum()/l)*100
accuracy, t_accuracy

(80.48387096774194, 78.22878228782288)

In [22]:
t_los = loss(model, t_data, t_targ).sum()/l
t_los

0.4383965436310818

In [23]:
def f1score(targ,pred):
    c = pred==1
    d = targ==1
    precision = (targ[c]*pred[c]).sum()/len(pred[c])
    recall = (targ[d]*pred[d]).sum()/len(targ[d])
    return (2*precision*recall)/(precision + recall)
f1score(targ,pred), f1score(t_targ,t_pred)

(0.7397849462365591, 0.6878306878306879)

In [24]:
print(f"Train Accuracy of model : {accuracy}%")
print(f"Test Accuracy of model : {t_accuracy}%")
print(f"Average NLLloss of model for Train data : {los}")
print(f"Average NLLloss of model for Test data : {t_los}")
print(f"F1score for Train data : {f1score(targ, pred)}")
print(f"F1score for Test data : {f1score(t_targ, t_pred)}")

Train Accuracy of model : 80.48387096774194%
Test Accuracy of model : 78.22878228782288%
Average NLLloss of model for Train data : 0.45014931060692775
Average NLLloss of model for Test data : 0.4383965436310818
F1score for Train data : 0.7397849462365591
F1score for Test data : 0.6878306878306879
